# Generated by Django 3.1.2 on 2020-10-31 11:55

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='no_image.jpg', upload_to='products/%Y/%m/%d'),
        ),
    ]
