# Generated by Django 3.1.2 on 2020-11-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_translations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
